version: "3.9"

services:
  web:
    image: python:latest
    command:
      - "-m"
      - "http.server"
      - "8000"
      - "--bind"
      - "0.0.0.0"
    ports:
      - "8000:8000"
  python:
    image: python:latest
